
baseurl: ""
url: "https://wenxinjiang2000.github.io"

title: "Wenxin Jiang"
description: "Wenxin Jiang is a Ph.D. student at Politecnico di Milano focusing on signal processing, Physics AI, and Prognostics and Health Management."

markdown: kramdown
future: true

plugins:
  - jekyll-email-protect
  - jekyll-sitemap

collections:
  - publications
  - news
  - showcase
  - posts
